// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: singer.proto

package signer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MtA部分
type MtARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K     []byte `protobuf:"bytes,1,opt,name=k,proto3" json:"k,omitempty"`
	Index int64  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *MtARequest) Reset() {
	*x = MtARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_singer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MtARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtARequest) ProtoMessage() {}

func (x *MtARequest) ProtoReflect() protoreflect.Message {
	mi := &file_singer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtARequest.ProtoReflect.Descriptor instead.
func (*MtARequest) Descriptor() ([]byte, []int) {
	return file_singer_proto_rawDescGZIP(), []int{0}
}

func (x *MtARequest) GetK() []byte {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *MtARequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type MtAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B []byte `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *MtAResponse) Reset() {
	*x = MtAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_singer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MtAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtAResponse) ProtoMessage() {}

func (x *MtAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_singer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtAResponse.ProtoReflect.Descriptor instead.
func (*MtAResponse) Descriptor() ([]byte, []int) {
	return file_singer_proto_rawDescGZIP(), []int{1}
}

func (x *MtAResponse) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

var File_singer_proto protoreflect.FileDescriptor

var file_singer_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x0a, 0x4d, 0x74, 0x41, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x01, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x1b, 0x0a, 0x0b, 0x4d, 0x74, 0x41, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x62, 0x32, 0x38, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x03, 0x4d, 0x74, 0x41, 0x12, 0x12, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e,
	0x4d, 0x74, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x2e, 0x4d, 0x74, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_singer_proto_rawDescOnce sync.Once
	file_singer_proto_rawDescData = file_singer_proto_rawDesc
)

func file_singer_proto_rawDescGZIP() []byte {
	file_singer_proto_rawDescOnce.Do(func() {
		file_singer_proto_rawDescData = protoimpl.X.CompressGZIP(file_singer_proto_rawDescData)
	})
	return file_singer_proto_rawDescData
}

var file_singer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_singer_proto_goTypes = []interface{}{
	(*MtARequest)(nil),  // 0: signer.MtARequest
	(*MtAResponse)(nil), // 1: signer.MtAResponse
}
var file_singer_proto_depIdxs = []int32{
	0, // 0: signer.Signer.MtA:input_type -> signer.MtARequest
	1, // 1: signer.Signer.MtA:output_type -> signer.MtAResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_singer_proto_init() }
func file_singer_proto_init() {
	if File_singer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_singer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MtARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_singer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MtAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_singer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_singer_proto_goTypes,
		DependencyIndexes: file_singer_proto_depIdxs,
		MessageInfos:      file_singer_proto_msgTypes,
	}.Build()
	File_singer_proto = out.File
	file_singer_proto_rawDesc = nil
	file_singer_proto_goTypes = nil
	file_singer_proto_depIdxs = nil
}
